services:
  best_it_commercetools_filter.model_search.search_config:
      class: BestIt\Commercetools\FilterBundle\Model\Search\SearchConfig
      factory: 'best_it_commercetools_filter.factory.search_config_factory:create'

  best_it_commercetools_filter.model_suggest.suggest_config:
      class: BestIt\Commercetools\FilterBundle\Model\Suggest\SuggestConfig
      factory: 'best_it_commercetools_filter.factory.suggest_config_factory:create'

  best_it_commercetools_filter.normalizer.array_product_normalizer:
      class: BestIt\Commercetools\FilterBundle\Normalizer\ArrayProductNormalizer

  best_it_commercetools_filter.normalizer.empty_product_normalizer:
      class: BestIt\Commercetools\FilterBundle\Normalizer\EmptyProductNormalizer

  best_it_commercetools_filter.factory.search_config_factory:
      class: BestIt\Commercetools\FilterBundle\Factory\SearchConfigFactory
      arguments:
          - '%best_it_commercetools_filter.config%'

  best_it_commercetools_filter.factory.suggest_config_factory:
      class: BestIt\Commercetools\FilterBundle\Factory\SuggestConfigFactory
      arguments:
          - '%best_it_commercetools_filter.config%'

  best_it_commercetools_filter.factory.search_context_factory:
      class: BestIt\Commercetools\FilterBundle\Factory\SearchContextFactory
      arguments:
          - '@best_it_commercetools_filter.model_search.search_config'
          - '@best_it_commercetools_filter.generator.url'

  best_it_commercetools_filter.factory.pagination_factory:
      class: BestIt\Commercetools\FilterBundle\Factory\PaginationFactory

  best_it_commercetools_filter.factory.sorting_factory:
      class: BestIt\Commercetools\FilterBundle\Factory\SortingFactory

  best_it_commercetools_filter.factory.facet_collection_factory:
      class: BestIt\Commercetools\FilterBundle\Factory\FacetCollectionFactory
      arguments:
          - '@best_it_commercetools_filter.model.facet_config_collection'
          - '@event_dispatcher'

  best_it_commercetools_filter.provider.empty_facet_config_provider:
      class: BestIt\Commercetools\FilterBundle\Provider\EmptyFacetConfigProvider

  best_it_commercetools_filter.manager.filter_manager:
      class: BestIt\Commercetools\FilterBundle\Manager\FilterManager
      arguments:
          - '@best_it_commercetools_filter.factory.search_context_factory'
          - '@best_it_commercetools_filter.factory.sorting_factory'
          - '@best_it_commercetools_filter.builder.request_builder'
          - '@best_it_commercetools_filter.builder.response_builder'

  best_it_commercetools_filter.manager.suggest_manager:
      class: BestIt\Commercetools\FilterBundle\Manager\SuggestManager
      arguments:
          - '@best_it_commercetools_filter.request.client'
          - '@best_it_commercetools_filter.normalizer.product'
          - '@event_dispatcher'
          - '@best_it_commercetools_filter.model_suggest.suggest_config'

  best_it_commercetools_filter.builder.request_builder:
      class: BestIt\Commercetools\FilterBundle\Builder\RequestBuilder
      arguments:
          - '@best_it_commercetools_filter.request.client'
          - '@best_it_commercetools_filter.model.facet_config_collection'
          - '@event_dispatcher'

  best_it_commercetools_filter.builder.response_builder:
      class: BestIt\Commercetools\FilterBundle\Builder\ResponseBuilder
      arguments:
          - '@best_it_commercetools_filter.normalizer.product'
          - '@best_it_commercetools_filter.factory.pagination_factory'
          - '@form.factory'
          - '@best_it_commercetools_filter.factory.facet_collection_factory'

  best_it_commercetools_filter.generator.default_filter_url_generator:
      class: BestIt\Commercetools\FilterBundle\Generator\DefaultFilterUrlGenerator
      arguments: ['@router']

  best_it_commercetools_filter.listener_term.enum_attribute_listener:
      class: BestIt\Commercetools\FilterBundle\Listener\Term\EnumAttributeListener
      arguments:
          - '@best_it_commercetools_filter.normalizer.enum'
      tags:
          - { name: kernel.event_subscriber }

  best_it_commercetools_filter.normalizer_term.enum_attribute_normalizer:
      class: BestIt\Commercetools\FilterBundle\Normalizer\Term\EnumAttributeNormalizer
      arguments:
          - '@best_it_commercetools_filter.request.client'
          - '@best_it_commercetools_filter.normalizer.enum.cache'
          - '%best_it_commercetools_filter.config.enum_normalizer.cache_life_time%'
          - '@best_it_commercetools_filter.commercetools.commons.helper.query_helper'

  best_it_commercetools_filter.listener_term.category_listener:
      class: BestIt\Commercetools\FilterBundle\Listener\Term\CategoryListener
      arguments:
          - '@best_it_commercetools_filter.normalizer.category'
      tags:
          - { name: kernel.event_subscriber }

  best_it_commercetools_filter.normalizer_term.category_normalizer:
      class: BestIt\Commercetools\FilterBundle\Normalizer\Term\CategoryNormalizer
      arguments:
          - '@best_it_commercetools_filter.request.client'
          - '@best_it_commercetools_filter.normalizer.category.cache'
          - '%best_it_commercetools_filter.config.category_normalizer.cache_life_time%'
          - '@best_it_commercetools_filter.commercetools.commons.helper.query_helper'

  best_it_commercetools_filter.commercetools.commons.helper.query_helper:
      class: Commercetools\Commons\Helper\QueryHelper

  best_it_commercetools_filter.form_extension.additional_filter_fields_extension:
      class: BestIt\Commercetools\FilterBundle\Form\Extension\AdditionalFilterFieldsExtension
      arguments:
          - '%best_it_commercetools_filter.config%'
      tags:
          - { name: form.type_extension, extended_type: BestIt\Commercetools\FilterBundle\Form\FilterType }