services:
  best_it_commercetools_filter.model.config:
      class: BestIt\Commercetools\FilterBundle\Model\Config
      factory: 'best_it_commercetools_filter.factory.config_factory:create'

  best_it_commercetools_filter.normalizer.array_product_normalizer:
      class: BestIt\Commercetools\FilterBundle\Normalizer\ArrayProductNormalizer

  best_it_commercetools_filter.normalizer.empty_product_normalizer:
      class: BestIt\Commercetools\FilterBundle\Normalizer\EmptyProductNormalizer

  best_it_commercetools_filter.factory.config_factory:
      class: BestIt\Commercetools\FilterBundle\Factory\ConfigFactory
      arguments:
          - '%best_it_commercetools_filter.config%'

  best_it_commercetools_filter.factory.context_factory:
      class: BestIt\Commercetools\FilterBundle\Factory\ContextFactory
      arguments:
          - '@best_it_commercetools_filter.model.config'
          - '@best_it_commercetools_filter.generator.url'

  best_it_commercetools_filter.factory.pagination_factory:
      class: BestIt\Commercetools\FilterBundle\Factory\PaginationFactory

  best_it_commercetools_filter.factory.sorting_factory:
      class: BestIt\Commercetools\FilterBundle\Factory\SortingFactory

  best_it_commercetools_filter.factory.facet_collection_factory:
      class: BestIt\Commercetools\FilterBundle\Factory\FacetCollectionFactory
      arguments:
          - '@best_it_commercetools_filter.model.facet_config_collection'
          - '@best_it_commercetools_filter.helper.enum_attribute_helper'

  best_it_commercetools_filter.provider.empty_facet_config_provider:
      class: BestIt\Commercetools\FilterBundle\Provider\EmptyFacetConfigProvider

  best_it_commercetools_filter.manager.filter_manager:
      class: BestIt\Commercetools\FilterBundle\Manager\FilterManager
      arguments:
          - '@best_it_commercetools_filter.factory.context_factory'
          - '@best_it_commercetools_filter.factory.sorting_factory'
          - '@best_it_commercetools_filter.builder.request_builder'
          - '@best_it_commercetools_filter.builder.response_builder'

  best_it_commercetools_filter.manager.suggest_manager:
      class: BestIt\Commercetools\FilterBundle\Manager\SuggestManager
      arguments:
          - '@best_it_commercetools_filter.request.client'
          - '@best_it_commercetools_filter.normalizer.product'
          - '@event_dispatcher'
          - '%best_it_commercetools_filter.mark_matching_variants%'

  best_it_commercetools_filter.builder.request_builder:
      class: BestIt\Commercetools\FilterBundle\Builder\RequestBuilder
      arguments:
          - '@best_it_commercetools_filter.request.client'
          - '@best_it_commercetools_filter.model.facet_config_collection'
          - '@event_dispatcher'
          - '%best_it_commercetools_filter.mark_matching_variants%'

  best_it_commercetools_filter.builder.response_builder:
      class: BestIt\Commercetools\FilterBundle\Builder\ResponseBuilder
      arguments:
          - '@best_it_commercetools_filter.normalizer.product'
          - '@best_it_commercetools_filter.factory.pagination_factory'
          - '@form.factory'
          - '@best_it_commercetools_filter.factory.facet_collection_factory'

  best_it_commercetools_filter.generator.default_filter_url_generator:
      class: BestIt\Commercetools\FilterBundle\Generator\DefaultFilterUrlGenerator
      arguments: ['@router']

  best_it_commercetools_filter.helper.enum_attribute_helper:
      class: BestIt\Commercetools\FilterBundle\Helper\EnumAttributeHelper
      arguments: ['@best_it_commercetools_filter.request.client', '@cache.app', '%best_it_commercetools_filter.cache_life_time%']